### ISSUE TITLE
Don't get the same output and it terminates immediately

### ISSUE THREAD

**Issue by mobluse** [MJoergen/cpu6502#1]
I don't get the same output as you and it terminates immediately. I use cc65 (2.16-2) installed using apt from most updated Ubuntu 18.04 from Microsoft Store running in WSL on Windows 10. Note: `make` also builds rom.bin without needing `make rom.bin`.
```
$ cpu6502
Initializing memory with 16384 bytes
Resetting CPU. PC=c000
Infinite loop!
26764730 instructions executed
```

**Comment by MJoergen** [comment]
Thank you for your comments. The program is actually simulating correctly, but I had disabled the trace output.

I've now updated the README (to note that rom.bin is automatically built) and re-enabled the trace output.
